# fly.toml app configuration file generated for pumppro-server on 2024-01-06T22:28:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pumppro-server"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command="npx prisma migrate deploy"
